---
title: "创造性思维1"
author: "王振"
date: "2025-01-25"
output: html_document
---

```{r 读取学生和创造性思维文件}
library(foreign)
 
# 定义文件路径
file1_path <- "C:\\Users\\王振\\Desktop\\CY08MSP_STU_QQQ副本.SAV"
file2_path <- "C:\\Users\\王振\\Desktop\\CY08MSP_CRT_COG副本.SAV"
 
# 读取SPSS文件
data1 <- read.spss(file1_path, to.data.frame = TRUE)  # to.data.frame = TRUE 是默认的，但可以明确写出
data2 <- read.spss(file2_path, to.data.frame = TRUE)
 
```


```{r 读取教师与学校数据}
library(foreign)
 
# 定义文件路径（请根据你的实际情况修改这些路径）
file3_path <- "C:\\Users\\王振\\Desktop\\CY08MSP_TCH_QQQ.SAV"
file4_path <- "C:\\Users\\王振\\Desktop\\CY08MSP_SCH_QQQ副本.SAV"
 
# 读取SPSS文件
data3 <- read.spss(file3_path, to.data.frame = TRUE)  # to.data.frame = TRUE 是默认的，但可以明确写出
data4 <- read.spss(file4_path, to.data.frame = TRUE)
 
```


```{r 合并学生与创造性思维数据}
library(dplyr)  
# 确保 CNTSTUID 在 data1 和 data2 中存在  
if ("CNTSTUID" %in% names(data1) & "CNTSTUID" %in% names(data2)) {  
  
    # 提取 data2 中的 CNTSTUID 值  
    cntstuid_values <- data2$CNTSTUID  
    
    # 在 data1 中找到与 data2 中相同 CNTSTUID 的整行数据  
    matched_rows <- data1 %>%  
      filter(CNTSTUID %in% cntstuid_values)  
    
    # 使用 match() 函数确保按 data2 中 CNTSTUID 的顺序排列  
    matched_rows <- matched_rows[match(cntstuid_values, matched_rows$CNTSTUID), ]  
    
    # 将提取的行添加到 data2 的后面  
    data2_extended <- bind_cols(data2, matched_rows)  
    
    # 打印出合并后的数据框的前几行以确认结果  
    print(head(data2_extended))  
} else {  
    print("CNTSTUID 在数据中未找到！")  
}
```


```{r 合并创造性思维、学生、家庭、学校数据}
# 假设 data2_extended 和 data4 已经被读取并存在  

# 进行合并，使用 data2_extended 中的 CNTSCHID...3 和 data4 中的 CNTSCHID 进行连接  
merged_data <- merge(data2_extended, data4, by.x = "CNTSCHID...2", by.y = "CNTSCHID", all.x = TRUE)  

# 输出合并后的数据框  
print(merged_data)
```


```{r 澳门数据}
# 安装并加载dplyr包
library(dplyr)

# 筛选数据
data6 <- merged_data %>%
  filter(CNTRYID == "Macao (China)")

# 查看筛选后的数据
head(data6)
```


```{r 澳门各学校频数}
# 如果CNTSCHID...2确实是变量名
table_result <- table(data6$CNTSCHID...2)
 
# 打印结果
print(table_result)
```


+无条件均值模型

```{r 零模型1}
library(lme4)
zero_model <- lmer(PV1CRTH_NC ~ 1 + (1 | CNTSCHID...2), data = data6)
summary(zero_model)
```


```{r 零模型（2）}
library(lme4)
zero_model <- lmer(PV1CRTH_NC ~  (1 | CNTSCHID...2), data = data6)
summary(zero_model)
```


```{r}
re1 <- summary(zero_model)
```


```{r 各学校残差图}
library(lattice)
bwplot(CNTSCHID...2 ~ resid(zero_model), merged_data)
```


```{r}
library(lattice)

# 确保zero_model已经被定义为一个有效的模型，并且可以从中提取残差
# 假设SchoolID是你想要用来分组的变量

# 提取残差
residuals <- resid(zero_model)

# 将残差添加到merged_data数据框中（如果它们不在同一个数据框中）
# 注意：这里假设residuals的长度与merged_data中的行数相匹配
merged_data$Residuals <- residuals

# 使用bwplot绘制箱线图
# 注意：这里使用~操作符来指定公式，左侧是Y轴变量，右侧是X轴变量（分组变量）
bwplot(Residuals ~ CNTSCHID...2, data = merged_data, xlab = "CNTSCHID...2", ylab = "Residuals")
```


```{r 各学校平均值}
with(merged_data, tapply(PV1CRTH_NC, CNTSCHID...2, mean))
```


```{r 各学校截距}
coef(zero_model)
```


+ 固定斜率，固定截距

```{r}
summary(lm(PV1CRTH_NC ~ CURIOAGR, data6))
```


```{r,fig.height=5}
fit.int <- lm(lm(PV1CRTH_NC ~ IMAGINE, merged_data))
plot(merged_data$IMAGINE,merged_data$PV1CRTH_NC)
abline(fit.int) 
```


+ 固定斜率，随机截距

```{r}
hlm.1 <- lmer(PV1CRTH_NC ~ CURIOAGR + (1|CNTSCHID...2), data6)
summary(hlm.1)
```


```{r}
coef(hlm.1)
```


```{r,echo = FALSE,fig.height=5}
with(hlm.1, {
  cc <- coef(hlm.1)$Subject
  xyplot(Reaction ~ Days | Subject, data = sleepstudy,
    index.cond = function(x, y) coef(lm(y ~ x))[1],
    panel = function(x, y, groups, subscripts, ...) {
      panel.grid(h = -1, v = -1)
      panel.points(x, y, ...)
      subj <- as.character(sleepstudy$Subject[subscripts][1])
      panel.abline(cc[subj,1], cc[subj, 2])                   
    })
})
```


```{r}
anova(hlm.null, hlm.1)
```


+ 随机斜率，固定截距

```{r}
hlm.3 <- lmer(PV1CRTH_NC ~ CURIOAGR + (0 + CURIOAGR|CNTSCHID...2), data6)
summary(hlm.3)
```


```{r}
coef(hlm.3)
```


```{r,echo = FALSE,fig.height=5}
with(hlm.3, {
  cc <- coef(hlm.3)$Subject
  xyplot(Reaction ~ Days | Subject, data = sleepstudy,
    index.cond = function(x, y) coef(lm(y ~ x))[1],
    panel = function(x, y, groups, subscripts, ...) {
      panel.grid(h = -1, v = -1)
      panel.points(x, y, ...)
      subj <- as.character(sleepstudy$Subject[subscripts][1])
      panel.abline(cc[subj,1], cc[subj, 2])                   
    })
})
```


+ 随机斜率，随机截距

```{r}
hlm.2 <- lmer(PV1CRTH_NC ~ CURIOAGR + (1+CURIOAGR|CNTSCHID...2), data6)
summary(hlm.2)
```


```{r}
coef(hlm.2)
```


```{r,echo = FALSE,fig.height=5}
with(hlm.2, {
  cc <- coef(hlm.2)$Subject
  xyplot(Reaction ~ Days | Subject, data = sleepstudy,
    index.cond = function(x, y) coef(lm(y ~ x))[1],
    panel = function(x, y, groups, subscripts, ...) {
      panel.grid(h = -1, v = -1)
      panel.points(x, y, ...)
      subj <- as.character(sleepstudy$Subject[subscripts][1])
      panel.abline(cc[subj,1], cc[subj, 2])                   
    })
})
```


```{r}
anova(hlm.1, hlm.2)
```


```{r r中读取数据保存为sav文件}
library(haven)
write_sav(merged_data, "C:\\Users\\王振\\Desktop\\merged_data.sav")
```

